# -*- coding: utf-8 -*-
"""Data Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fT8qkonlE8pKMbAFczmJMGGr-Zb2EDZP

```
# This is formatted as code
```

# Perform EDA using descriptive statistics and visualizations
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

dataset=pd.read_csv("/content/RESTAURANT_DATA_5K (1).csv")
display(dataset.head())

print("Basic Stats:\n", dataset.describe())

#Top Locations by Average Rating
location_rating = dataset.groupby("Restaurant location")["Rating"].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10,6))
sns.barplot(x=location_rating.values, y=location_rating.index, palette="viridis")
plt.title("Top 10 Restaurant Locations by Average Rating")
plt.xlabel("Average Rating")
plt.ylabel("Location")
plt.tight_layout()
plt.show()

"""# Analyze trends related to successful restaurant locations"""

#Footfall vs Rating
plt.figure(figsize=(8,6))
sns.scatterplot(data=dataset, x='Footfall', y='Rating', hue='Parking Availability', alpha=0.5)
plt.title("Footfall vs Rating (Color = Parking Availability)")
plt.show()

# Rating vs Distance from City Centre
plt.figure(figsize=(8,6))
sns.boxplot(data=dataset, x=pd.cut(dataset['Distance from city Centre'], bins=5), y='Rating')
plt.title("Rating vs Distance from City Centre")
plt.xlabel("Distance Range")
plt.ylabel("Rating")
plt.show()

# Rating by Cuisine Type (top 10)
top_cuisines = dataset['Cuisines Type'].value_counts().head(10).index
plt.figure(figsize=(10,6))
sns.boxplot(data=dataset[dataset['Cuisines Type'].isin(top_cuisines)],
            x='Cuisines Type', y='Rating')
plt.xticks(rotation=45)
plt.title("Rating Distribution by Cuisine Type (Top 10)")
plt.tight_layout()
plt.show()

"""*italicised text*#Summarize findings with charts and narrative explanation"""

# Summary insights (example print statements)
print("🔸 Restaurants near transport hubs tend to have higher success ratings.")
print("🔸 Higher population density correlates with greater restaurant success.")
print("🔸 Areas with moderate competition show better average performance.")

"""#4. Feature Engineering

"""

